timeline
title Timeline of Project Munchie
section Learning
2nd December - 6th December : Flutter
6th December - 7th December : Prisma
7th December - 8th December : GraphQL
8th December - 11th December : Deno - Hono : Ansible

section Planning
12th December : Feature Planning : Mindmap : Use Case Diagram : Figma
13th December : Entity Diagram : API Documentation : Architecture Diagram

section Development
13th December : Prisma : GraphQL
14th December - 16th December : User Authentication
17th December - 20th December : Munchie CRUD
21th December - 24th December : Munchie Finder API
25th December - 27th December : Munchie Recommender
28th Decemeber - 30th December : Settings and Deals

section Deployment
31st - 3rd Jan : Terraform
4th Jan : Ansible : Istio
5th Jan : CICD
